### PR TITLE
updates to kemono.party file page parser

### PR DESCRIPTION
**Pull request by tokumeiii**
When an artist posted a link where the link text itself was the URL the link leads to, the parser would generate two URLs to follow, one of which had HTML garbage in it that made it unusable (i.e. you'd get both `https://link.to/stuff` and `https://link.to/stuff</a></p>`). This changes the parser to specifically select the URL parsed from the tag's href text so it will only generate one URL per link.

### CODE REVIEW

**Comment by CuddleBear92** [comment]
care to give some example post urls to test it on for this?

**Comment by tokumeiii** [comment]
Here is a link for the previously mentioned URL parsing issue: [https://kemono.party/patreon/user/3506306/post/52615502](https://kemono.party/patreon/user/3506306/post/52615502) (NSFW)

In addition to that I made two more changes which apparently it's adding to this pull request automatically (I'm a bit of an idiot when it comes to git).

The first is an issue where older files which are given with absolute paths in the JSON would have malformed URLs due to `https://data.kemono.party` being appended to the front (resulting in URLs of the form `https://data.kemono.partyhttps://kemono.party/path/to/file`). This is done with a regex that checks for this type of malformed URL and corrects it by removing the `https://kemono.party` part. Here's an example URL for this: [https://kemono.party/patreon/user/3506306/post/28732993](https://kemono.party/patreon/user/3506306/post/28732993) (also NSFW)

This also improves URL parsing from body text by cleaning up extraneous text that can end up in front of the URL. I noticed this problem in the URL that was provided as an example in the parser itself ([https://kemono.party/fanbox/user/314223/post/861054](https://kemono.party/fanbox/user/314223/post/861054), again NSFW). The parser would find a line with a dropbox URL on it, but it would have a bunch of junk in front of it which resulted in passing a malformed URL to the gallery downloader.

**Comment by CuddleBear92** [comment]
just to verify, you used the last release i did of this as a base right? if so then ill just confirm it as is. :)

**Comment by tokumeiii** [comment]
Yes, all of this is based on 2021-07-13 v2.

**Comment by CuddleBear92** [comment]
yeah, i checked. thanks for the help. please keep working on it if you want too or find issues. 
we prob should build a larger list of test posts and creators that we can throubleshoot with. 

For example i need more password examples as currently it only looks for the word password or pass to find it and grab the full line in question.

**Pull request merged**
