### PR TITLE
Added minitokyo downloader

### PR DESCRIPTION
**Pull request by tcheerno**
Hi, so is a downloader for minitokyo. It has 3 separate GUGs, for reasons written in readme. To summarize, minitokyo hosts three types of files (wallpapers, scans, fanarts), and actual browsing is done with a numerical tag id. So you need to chose from three GUGs and use the tag id for it to work.

Let me know if you think something can be improved.

### CODE REVIEW

**Comment by Zweibach** [comment]
Add date to filename and title in the ISO format, example 2021-04-23.

Also add the following block to the top of the readme:
```
[See the help files for how to add downloaders to Hydrus](https://hydrusnetwork.github.io/hydrus/help/adding_new_downloaders.html)
```
Because yes, people really do ask how to add downloaders.

**Comment by tcheerno** [comment]
@Zweibach Done. Please take a look.

**Comment by Zweibach** [comment]
When I said "example 2021-04-23" I meant the specific date, not the formatting. See: https://en.wikipedia.org/wiki/ISO_8601#Calendar_dates

**Comment by tcheerno** [comment]
@Zweibach done.

**Pull request merged**
