### PR TITLE
Add parsers/URL classes for /v/idyart.booru.org and consoletan.booru.org

### PR DESCRIPTION
**Pull request by Difegue**
The /v/idyart parser is one size fits all and can probably be used as-is in a bunch of other booru.org websites.

### CODE REVIEW

**Comment by DonaldTsang** [comment]
Then write an auto-generator for the other booru.org sites?

**Comment by Robert99943** [comment]
I believe the [Gelbooru 0.1.11 parser](https://github.com/CuddleBear92/Hydrus-Presets-and-Scripts/blob/master/Download%20System/Parsers/gelbooru%200.1.11%20file%20page%20parser.txt) should work for /v/idyart along with most other booru.org websites. As well as the [booru.org URL classes](https://github.com/CuddleBear92/Hydrus-Presets-and-Scripts/blob/master/Download%20System/URL%20Classes/booru.org%20post%20page.txt) should work with all booru.org websites on their domain, each subdomain doesn't necessarily need its own URL class.

**Comment by DonaldTsang** [comment]
@Robert99943 simply packaging the three scripts into an all-in-one with corrected sub-script names would be great.

**Comment by CuddleBear92** [comment]
We already have an all in one preset containing everything you need outside of the gug to sub domain specifically in the form of the meme.booru.org all in one file which is just the gelbooru 0.1.11 gallery and post parsers with an booru.org url class and a single gug for the meme sub domain. All other gugs is already generated and there already is an gug generating script. 

All the gallery and post url classes can share a single class as it is all the same outside of the sub domain.

**Comment by DonaldTsang** [comment]
@CuddleBear92 I think I found a way to auto-generate the script
1. scrape the front page of `*.booru.org`, find the `<p>` tags
2. Regex search `/(?<=Running Gelbooru )(0.1.11|0.2)/` to get the version number
3. Apply script combination, and substituting the right names and variables
4. Presto!

**Comment by CuddleBear92** [comment]
Usage of 0.2 is rare and is already linked in the parsers with the correct urls. Everything else is using 0.1.11. And we already have a list of all the booru sites with a script to make the gug. Really no need to make anything else unless you make it. Until that point it's all talk. 

All of this has already been done. All the required scripts and presets is already been made.

**Comment by DonaldTsang** [comment]
So these are the components:
- The Gallery Parser (furry@booru.org) https://github.com/CuddleBear92/Hydrus-Presets-and-Scripts/blob/master/Download%20System/Parsers/gelbooru%200.2.x%20gallery%20page%20parser.txt
- Page parser for 0.1.11 (meme@booru.org) https://github.com/CuddleBear92/Hydrus-Presets-and-Scripts/blob/master/Download%20System/Parsers/gelbooru%200.1.11%20file%20page%20parser.txt
- Page parser for 0.2 (furry@booru.org) https://github.com/CuddleBear92/Hydrus-Presets-and-Scripts/blob/master/Download%20System/Parsers/gelbooru%200.2.0%20file%20page%20parser.txt
- File URL https://github.com/CuddleBear92/Hydrus-Presets-and-Scripts/blob/master/Download%20System/URL%20Classes/booru.org%20file%20url.txt
- Post Page (rm.booru.org) https://github.com/CuddleBear92/Hydrus-Presets-and-Scripts/blob/master/Download%20System/URL%20Classes/booru.org%20post%20page.txt
- Search Gallery (meme@booru.org is in it) https://github.com/CuddleBear92/Hydrus-Presets-and-Scripts/blob/master/Download%20System/URL%20Classes/booru.org%20search%20gallery.txt
What do each of these script correspond to? And which ones only uses the booru.org as sample links? Which ones NEED me to input *.booru.org links in order for it to function?

**Comment by DonaldTsang** [comment]
Small note here
```
from urllib2 import urlopen
from bs4 import BeautifulSoup
from re import search

def versioning(subdomain):
  quote_page = "https://" + subdomain + ".booru.org" # site build
  print(quote_page)
  page = urlopen(quote_page) # opening
  soup = BeautifulSoup(page, "html.parser") # parsing
  name_box = soup.find("p") # find the label
  name = name_box.text.strip() # get text
  print(name)
  version = search(r"(?<=Running Gelbooru )(Beta 0.1.11|0.2)", name) # extract
  return version.group(0)

def json_gen(subdomain):
  v = versioning(subdomain)
  if v == "Beta 0.1.11":
    return 1 # where the code goes
  else if v == "0.2":
    return 2 # where the code goes
```

**Comment by DonaldTsang** [comment]
@CuddleBear92 I am trying to get this https://github.com/CuddleBear92/Hydrus-Presets-and-Scripts/blob/master/Download%20System/All-in-Ones/Single-Sites/easy-import-meme%40booru.org-tag-search-2018.09.21.png
and turn it into any all-in-one for any of the 0.1.11 booru.org site, regex could do it I am sure. Could you get me the text file of that?

**Comment by Difegue** [comment]
I thought meme@booru.org was only for a specific booru.org subdomain and didn't look in the scripts folder like an idiot - sorry for the useless PR!  

Documentation of this repo is a bit outdated as to what's supported and where to find it -- might do a cleanup PR instead later. 🙂

**Pull request closed without merging**
